apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1-container
          image: us-central1-docker.pkg.dev/my-kubernates-project-412710/codelabrepo/service-one:v3
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /api/v1/receive1
              port: http
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /api/v1/receive1
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
