apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2-container
          image: us-central1-docker.pkg.dev/my-kubernates-project-412710/codelabrepo/service-two:v3
          ports:
            - containerPort: 9090
              name: http
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          readinessProbe:
            httpGet:
              path: /api/v2/receive2
              port: http
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /api/v2/receive2
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
