apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-preload-data-config
  labels:
    name: mysql-data-store
    app: mysql-gke-deployment
  namespace: default
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS`product`;
    USE `product`;
    DROP TABLE IF EXISTS `product`;
    CREATE TABLE `product`(
     `id`int NOT NULL AUTO_INCREMENT,
     `name`varchar(255) NOT NULL,
     `description`varchar(255) NOT NULL,
     `price`varchar(255) DEFAULT NULL,
     `created_at`datetime DEFAULT CURRENT_TIMESTAMP,
     `created_by`varchar(255) DEFAULT NULL,
     `updated_at`datetime DEFAULT CURRENT_TIMESTAMP,
     `updated_by` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    );
    insert into product(`name`,`description`,`price`) values('Mobile','Iphone 15','100000');`
